"""Increase QR code column size

Revision ID: a93b02ab81ba
Revises: 830ac4983f65
Create Date: 2025-03-12 01:48:27.160217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a93b02ab81ba'
down_revision = '830ac4983f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the existing index first
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index('qr_code')  # Drop the existing index

    # Now alter the column
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('qr_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)


        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index('qr_code', ['qr_code'], unique=True)
        batch_op.alter_column('qr_code',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
